<?xml version="1.0"?>
<package format="3">
  <name>indoor_gimbal_controller</name>
  <version>0.0.1</version>
  <description>Topotek UDP driver + operator GUI</description>
  <maintainer email="jacopo.vivaldi@tii.ae">Jacopo Vivaldi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>gstreamer1.0-tools</exec_depend>
  <exec_depend>gstreamer1.0-plugins-base</exec_depend>
  <exec_depend>gstreamer1.0-plugins-good</exec_depend>
  <exec_depend>gstreamer1.0-plugins-bad</exec_depend>
  <exec_depend>gstreamer1.0-libav</exec_depend>

  <!-- If your GUI uses PyQt -->
  <!-- <exec_depend>python3-pyqt5</exec_depend> -->

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
